サインアップ機能
shinonome-inc/backend-final-assignment-Keitaro pull request #1
Opened 2023-11-11 15:32 UTC by KeitaroYabu

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-11-13 07:02 UTC, KeitaroYabu commented on .cspell.json
> +{
スペルエラーがうざいので導入しました。

2023-11-13 07:02 UTC, KeitaroYabu commented on Makefile
> +run:
コマンドを打つのが面倒なので導入しました。

2023-11-19 05:03 UTC, masaya09 requested changes

2023-11-19 05:03 UTC, masaya09 commented on templates/accounts/signup.html
> +{% block title %}Sign Up{% endblock %} ← titleを入れる
![must-badge](https://img.shields.io/badge/review-must-red.svg)
画面上に表示されてしまうので不要な文字は削除してください

2023-11-19 05:03 UTC, masaya09 commented on accounts/tests.py
> +        )
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
修正不要ですが、テストは準備・実行・検証の3つの段階があり、それに応じて1行空欄を空けておくと確認しやすくなります。

```suggestion
    def test_success_post(self):
        valid_data = {
            "username": "testuser",
            "email": "test@example.com",
            "password1": "testpassword",
            "password2": "testpassword",
        }
        
        response = self.client.post(self.url, valid_data)
        
        self.assertRedirects(
            response,
            reverse("tweets:home"),
            status_code=302,
            target_status_code=200,
        )

```

2023-11-19 05:03 UTC, masaya09 commented on accounts/admin.py
> +from .models import User
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
Userはaccounts.modelsからimportするか、get_user_modelから取ってくるかはどちらかに統一した方が良いですね。

2023-11-19 05:03 UTC, masaya09 commented on accounts/views.py
> +        user = authenticate(self.request, username=username, password=password)
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
なぜauthenticateを用いるのか説明してみてください

2023-11-20 14:27 UTC, KeitaroYabu commented on accounts/views.py
> +        user = authenticate(self.request, username=username, password=password)
認証できるようにするため。

2023-11-20 14:30 UTC, KeitaroYabu commented on accounts/views.py
> +        user = authenticate(self.request, username=username, password=password)
https://man.plustar.jp/django/topics/auth/default.html

2023-11-22 01:32 UTC, masaya09 approved these changes
![BB8 Thumbs Up](https://media0.giphy.com/media/2cRLQokbuIWB7YTGVt/giphy.gif?cid=47028fa81rda1t2f7b12e0cyh0rlj4hnehstygaulemz4h55&ep=v1_gifs&rid=giphy.gif&ct=g)

2023-11-22 01:33 UTC, merged